{
 "title": "Traefik Log Service",
 "description": "Traeifk access logs with service filter is visualized. If the request couldn't be successfull, for example if service is down and coming request couldn't reach the service, this request will not be visualized.",
 "tags": [
  "loki",
  "traefik",
  "log",
  "service"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "traefik_service",
    "label": "traefik_service",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "Visitor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Unique Visitors",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "count(count_over_time({service_name=\"label-job-traefik-access-log\"} | json | ServiceName=~\".*${traefik_service}.*\" | label_format ID=`{{.ClientHost}}` | keep ID [${__range}]))"
    }
   ]
  },
  {
   "title": "Total Visit",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({service_name=\"label-job-traefik-access-log\"} | json | ServiceName=~\".*${traefik_service}.*\" [${__range}]))"
    }
   ]
  },
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({service_name=\"label-job-traefik-access-log\"} | json | ServiceName=~\".*${traefik_service}.*\"  [$__auto]))"
    }
   ]
  },
  {
   "title": "Request Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"label-job-traefik-access-log\"} | json | ServiceName=~\".*${traefik_service}.*\" | line_format \"- [{{.ClientUsername}}] - [{{.RequestAddr}}] - [{{.OriginStatus}}] - [{{.RequestPath}}] - [{{.ClientHost}}] - [{{.ServiceName}}]\""
    }
   ]
  }
 ]
}