{
 "title": "Traefik Metrics",
 "tags": [
  "traefik",
  "metrics"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "panels": [
  { "title": "Service Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(traefik_service_server_up) "
    }
   ]
  },
  {
   "title": "Healthy",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(traefik_service_server_up == 1) "
    }
   ]
  },
  {
   "title": "Unhealthy",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(traefik_service_server_up) - count(traefik_service_server_up == 1)"
    }
   ]
  },
  { "title": "Service Health Check", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Service Health",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "traefik_service_server_up", "legendFormat": "{{service}}" }
   ]
  },
  {
   "title": "Service Health (Percentage)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "traefik_service_server_up", "legendFormat": "{{service}}" }
   ]
  },
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Total Router Request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(traefik_router_requests_total{job=\"traefik\", service=~\".*\"}) by (service)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Service Request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(traefik_service_requests_total{job=\"traefik\", service=~\".*\"}) by (service)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}