{
 "title": "Trfk Logs",
 "tags": [
  "trfk",
  "log"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "service_name",
    "label": "Service",
    "query": "portfolio, portainer:9000, grafana:3000, "
   }
  ]
 },
 "panels": [
  { "title": "Visitor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Unique Visitors",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "count(count_over_time({service_name=\"traefik\"} | json | ServiceAddr=~\"${service_name}\" | label_format ID=`{{.ClientHost}}{{.request_User_Agent}}` | keep ID [${__range}]))"
    }
   ]
  },
  {
   "title": "Total Visit",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({service_name=\"traefik\"} | json | ServiceAddr=~\"${service_name}\" [${__range}]))"
    }
   ]
  },
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({service_name=\"traefik\"} | json | ServiceAddr=~\"${service_name}\" [$__auto])) by (detected_level)"
    }
   ]
  },
  {
   "title": "All Requests",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"traefik\"} | json | ServiceAddr=~\"${service_name}\" | line_format \"[{{.time}}] - [{{.ClientUsername}}] - [{{.ServiceAddr}}] - [{{.OriginStatus}}] - [{{.RequestPath}}] - [{{.ClientHost}}]\""
    }
   ]
  }
 ]
}