{
 "title": "trfk",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "auto",
 "panels": [
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Router Request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(traefik_router_requests_total{job=\"traefik\", service=~\".*\"}) by (service)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Service Request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(traefik_service_requests_total{job=\"traefik\", service=~\".*\"}) by (service)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Total Service Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(traefik_service_server_up) "
    }
   ]
  },
  {
   "title": "Healthy Service Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(traefik_service_server_up == 1) "
    }
   ]
  },
  {
   "title": "Unhealthy Service Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(traefik_service_server_up == 0) "
    }
   ]
  },
  {
   "title": "Service Health",
   "type": "gauge",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "traefik_service_server_up", "legendFormat": "{{service}}" }
   ]
  },
  {
   "title": "Service Health (Percentage)",
   "type": "gauge",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "traefik_service_server_up", "legendFormat": "{{service}}" }
   ]
  }
 ]
}