####################################### Services
services:
  grafana:
    image: grafana/grafana
    container_name: monitor-grafana-c
    volumes:
      - ./mount:/var/lib/grafana
      - ./provisioning/dashboards/:/etc/grafana/provisioning/dashboards/
      - ./provisioning/datasources/:/etc/grafana/provisioning/datasources/
    env_file:
      - ./.env
    networks:
      - network-monitor
    restart: always
    # ports:
    #   - 3000:3000

####################################### Networks
networks:
  network-monitor:
    external: true
